version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: url_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=urldb
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app  
  api:
    image: node:16
    restart: always
    container_name: url_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app  
    links:
      - db
    depends_on:
      - db
    command: yarn dev
